apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yealink-provision
  annotations:
    kubernetes.io/ingress.class: "nginx"    
#    certmanager.k8s.io/cluster-issuer: letsencrypt-staging

spec:
#  tls:
#  - hosts:
#    - yealink-provision.apis.simpsonlabs.net
#    secretName: yealink-provision-cert-secret
  rules:
  - host: yealink-provision.apis.simpsonlabs.net
    http:
      paths:
      - path: /
        backend:
          serviceName: yealink-provision
          servicePort: 80
